/var/log/suricata/stats.log
/var/log/suricata/suricata.log
{
    daily
    rotate 7
    missingok
    compress
    dateext
    dateformat -%Y-%m-%d
    copytruncate
    sharedscripts
    postrotate
        /bin/kill -HUP $(cat /var/run/suricata.pid)
    endscript
}
