/var/log/suricata/eve.json
{
    hourly
    size 5G
    rotate 48
    missingok
    compress
    dateext
    dateformat -%Y-%m-%d-%H-%M-%S
    copytruncate
    sharedscripts
    postrotate
        /bin/kill -HUP $(cat /var/run/suricata.pid)
    endscript
}
